version: '2'

services:

  nginx-proxy-server:
    image: nginx
    container_name: nginx-proxy-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vol_conf:/etc/nginx/conf.d
      - vol_vhost:/etc/nginx/vhost.d
      - vol_html:/usr/share/nginx/html
      - vol_certs:/etc/nginx/certs:ro
    restart: always

  docker-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-proxy-gen
    depends_on:
      - nginx-proxy-server
    volumes_from:
      - nginx-proxy-server
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy-server
      - docker-gen
    volumes_from:
      - nginx-proxy-server
    volumes:
      - vol_certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
    restart: always

volumes:
  vol_conf:
  vol_vhost:
  vol_html:
  vol_certs:

networks:
  default:
    external:
      name: nginx-proxy
